package fr.qui.gestion.v2.enumeration.CategorieFrais;

public enum CategorieFrais {
    TAXE_FONCIERE,
    IMPOTS_SUR_LE_REVENU,
    CHARGES_COPROPRIETE,
    ASSURANCE_PROPRIETAIRE,
    FRAIS_GESTION_LOCATIVE,
    ENTRETIEN,
    TRAVAUX,
    REMBOURSEMENT_PRET,
    IMPOTS_SUR_LOYER,
    FRAIS_NOTARIAUX,
    FRAIS_AGENT_IMMO,
    DEPENSES_OCCASIONNELLES,
    FRAIS_DIVERS
}
